"""Schedule C expense categories and default merchant-to-category lookup table."""

from __future__ import annotations

# 19 IRS Schedule C expense categories with their line numbers
SCHEDULE_C_CATEGORIES: list[dict[str, str]] = [
    {"name": "Advertising", "line": "8"},
    {"name": "Car and Truck Expenses", "line": "9"},
    {"name": "Commissions and Fees", "line": "10"},
    {"name": "Contract Labor", "line": "11"},
    {"name": "Depletion", "line": "12"},
    {"name": "Depreciation and Section 179", "line": "13"},
    {"name": "Employee Benefit Programs", "line": "14"},
    {"name": "Insurance", "line": "15"},
    {"name": "Interest", "line": "16"},
    {"name": "Legal and Professional Services", "line": "17"},
    {"name": "Office Expenses", "line": "18"},
    {"name": "Pension and Profit-Sharing Plans", "line": "19"},
    {"name": "Rent or Lease", "line": "20"},
    {"name": "Repairs and Maintenance", "line": "21"},
    {"name": "Supplies", "line": "22"},
    {"name": "Taxes and Licenses", "line": "23"},
    {"name": "Travel and Meals", "line": "24"},
    {"name": "Utilities", "line": "25"},
    {"name": "Other Expenses", "line": "27a"},
]

# Quick lookup: category name → Schedule C line number
CATEGORY_LINE: dict[str, str] = {cat["name"]: cat["line"] for cat in SCHEDULE_C_CATEGORIES}

# ---------------------------------------------------------------------------
# Default merchant lookup table (~200 entries).
# Keys are lowercase, stripped merchant names (or common substrings).
# Values are category names from SCHEDULE_C_CATEGORIES.
# ---------------------------------------------------------------------------
MERCHANT_LOOKUP: dict[str, str] = {
    # ── Advertising (Line 8) ────────────────────────────────────────────────
    "google ads": "Advertising",
    "google adwords": "Advertising",
    "facebook ads": "Advertising",
    "meta ads": "Advertising",
    "instagram ads": "Advertising",
    "linkedin ads": "Advertising",
    "linkedin marketing": "Advertising",
    "twitter ads": "Advertising",
    "x ads": "Advertising",
    "tiktok ads": "Advertising",
    "yelp advertising": "Advertising",
    "yelp for business": "Advertising",
    "mailchimp": "Advertising",
    "constant contact": "Advertising",
    "sendinblue": "Advertising",
    "activecampaign": "Advertising",
    "hootsuite": "Advertising",
    "buffer": "Advertising",
    "sprout social": "Advertising",
    "99designs": "Advertising",

    # ── Car and Truck Expenses (Line 9) ─────────────────────────────────────
    "uber": "Car and Truck Expenses",
    "lyft": "Car and Truck Expenses",
    "enterprise rent-a-car": "Car and Truck Expenses",
    "enterprise": "Car and Truck Expenses",
    "hertz": "Car and Truck Expenses",
    "avis": "Car and Truck Expenses",
    "budget car rental": "Car and Truck Expenses",
    "national car rental": "Car and Truck Expenses",
    "alamo": "Car and Truck Expenses",
    "dollar car rental": "Car and Truck Expenses",
    "thrifty car rental": "Car and Truck Expenses",
    "shell": "Car and Truck Expenses",
    "chevron": "Car and Truck Expenses",
    "exxon": "Car and Truck Expenses",
    "exxonmobil": "Car and Truck Expenses",
    "mobil": "Car and Truck Expenses",
    "bp": "Car and Truck Expenses",
    "sunoco": "Car and Truck Expenses",
    "76 gas": "Car and Truck Expenses",
    "circle k": "Car and Truck Expenses",
    "speedway": "Car and Truck Expenses",
    "wawa": "Car and Truck Expenses",
    "quiktrip": "Car and Truck Expenses",
    "racetrac": "Car and Truck Expenses",
    "pilot flying j": "Car and Truck Expenses",
    "loves travel stops": "Car and Truck Expenses",
    "jiffy lube": "Car and Truck Expenses",
    "midas": "Car and Truck Expenses",
    "firestone": "Car and Truck Expenses",
    "pep boys": "Car and Truck Expenses",
    "ez pass": "Car and Truck Expenses",
    "fastrak": "Car and Truck Expenses",
    "e-zpass": "Car and Truck Expenses",

    # ── Commissions and Fees (Line 10) ──────────────────────────────────────
    "stripe": "Commissions and Fees",
    "paypal": "Commissions and Fees",
    "square": "Commissions and Fees",
    "shopify": "Commissions and Fees",
    "etsy": "Commissions and Fees",
    "ebay": "Commissions and Fees",
    "amazon seller": "Commissions and Fees",
    "braintree": "Commissions and Fees",
    "venmo business": "Commissions and Fees",

    # ── Contract Labor (Line 11) ─────────────────────────────────────────────
    "upwork": "Contract Labor",
    "fiverr": "Contract Labor",
    "toptal": "Contract Labor",
    "guru": "Contract Labor",
    "freelancer": "Contract Labor",
    "99dollar": "Contract Labor",

    # ── Insurance (Line 15) ──────────────────────────────────────────────────
    "hiscox": "Insurance",
    "next insurance": "Insurance",
    "simply business": "Insurance",
    "cna insurance": "Insurance",
    "travelers": "Insurance",
    "hartford": "Insurance",
    "state farm": "Insurance",
    "allstate": "Insurance",
    "nationwide": "Insurance",
    "progressive": "Insurance",
    "geico": "Insurance",

    # ── Legal and Professional Services (Line 17) ────────────────────────────
    "legalzoom": "Legal and Professional Services",
    "rocket lawyer": "Legal and Professional Services",
    "turbotax": "Legal and Professional Services",
    "h&r block": "Legal and Professional Services",
    "hrblock": "Legal and Professional Services",
    "bench": "Legal and Professional Services",
    "quickbooks": "Legal and Professional Services",
    "freshbooks": "Legal and Professional Services",
    "xero": "Legal and Professional Services",
    "wave": "Legal and Professional Services",
    "honeybook": "Legal and Professional Services",
    "bonsai": "Legal and Professional Services",

    # ── Office Expenses (Line 18) ────────────────────────────────────────────
    "adobe": "Office Expenses",
    "adobe creative cloud": "Office Expenses",
    "microsoft": "Office Expenses",
    "microsoft 365": "Office Expenses",
    "office depot": "Office Expenses",
    "officemax": "Office Expenses",
    "staples": "Office Expenses",
    "fedex office": "Office Expenses",
    "ups store": "Office Expenses",
    "usps": "Office Expenses",
    "fedex": "Office Expenses",
    "ups": "Office Expenses",
    "dhl": "Office Expenses",
    "dropbox": "Office Expenses",
    "box": "Office Expenses",
    "google workspace": "Office Expenses",
    "gsuite": "Office Expenses",
    "slack": "Office Expenses",
    "zoom": "Office Expenses",
    "docusign": "Office Expenses",
    "hellosign": "Office Expenses",
    "notion": "Office Expenses",
    "airtable": "Office Expenses",
    "monday.com": "Office Expenses",
    "asana": "Office Expenses",
    "trello": "Office Expenses",
    "basecamp": "Office Expenses",
    "evernote": "Office Expenses",
    "1password": "Office Expenses",
    "lastpass": "Office Expenses",
    "grammarly": "Office Expenses",
    "canva": "Office Expenses",
    "figma": "Office Expenses",
    "sketch": "Office Expenses",
    "invision": "Office Expenses",
    "loom": "Office Expenses",
    "calendly": "Office Expenses",
    "typeform": "Office Expenses",
    "surveymonkey": "Office Expenses",
    "zapier": "Office Expenses",
    "make": "Office Expenses",
    "github": "Office Expenses",
    "gitlab": "Office Expenses",
    "atlassian": "Office Expenses",
    "jira": "Office Expenses",
    "confluence": "Office Expenses",
    "aws": "Office Expenses",
    "amazon web services": "Office Expenses",
    "google cloud": "Office Expenses",
    "microsoft azure": "Office Expenses",
    "digitalocean": "Office Expenses",
    "linode": "Office Expenses",
    "vultr": "Office Expenses",
    "cloudflare": "Office Expenses",
    "heroku": "Office Expenses",
    "netlify": "Office Expenses",
    "vercel": "Office Expenses",
    "twilio": "Office Expenses",
    "sendgrid": "Office Expenses",
    "mailgun": "Office Expenses",
    "new relic": "Office Expenses",
    "datadog": "Office Expenses",
    "sentry": "Office Expenses",
    "pagerduty": "Office Expenses",
    "linear": "Office Expenses",
    "clickup": "Office Expenses",
    "hubspot": "Office Expenses",

    # ── Rent or Lease (Line 20) ──────────────────────────────────────────────
    "wework": "Rent or Lease",
    "regus": "Rent or Lease",
    "industrious": "Rent or Lease",
    "iwg": "Rent or Lease",
    "spaces": "Rent or Lease",
    "knotel": "Rent or Lease",
    "coworking": "Rent or Lease",

    # ── Repairs and Maintenance (Line 21) ────────────────────────────────────
    "ubreakifix": "Repairs and Maintenance",
    "apple store": "Repairs and Maintenance",
    "best buy geek squad": "Repairs and Maintenance",
    "geek squad": "Repairs and Maintenance",
    "ifixit": "Repairs and Maintenance",

    # ── Supplies (Line 22) ───────────────────────────────────────────────────
    "amazon": "Supplies",
    "costco": "Supplies",
    "sams club": "Supplies",
    "sam's club": "Supplies",
    "target": "Supplies",
    "walmart": "Supplies",
    "ikea": "Supplies",
    "uline": "Supplies",

    # ── Travel and Meals (Line 24) ───────────────────────────────────────────
    "delta": "Travel and Meals",
    "delta airlines": "Travel and Meals",
    "united airlines": "Travel and Meals",
    "american airlines": "Travel and Meals",
    "southwest airlines": "Travel and Meals",
    "jetblue": "Travel and Meals",
    "alaska airlines": "Travel and Meals",
    "spirit airlines": "Travel and Meals",
    "frontier airlines": "Travel and Meals",
    "british airways": "Travel and Meals",
    "lufthansa": "Travel and Meals",
    "air france": "Travel and Meals",
    "emirates": "Travel and Meals",
    "airbnb": "Travel and Meals",
    "vrbo": "Travel and Meals",
    "hotels.com": "Travel and Meals",
    "expedia": "Travel and Meals",
    "booking.com": "Travel and Meals",
    "marriott": "Travel and Meals",
    "hilton": "Travel and Meals",
    "hyatt": "Travel and Meals",
    "ihg": "Travel and Meals",
    "wyndham": "Travel and Meals",
    "best western": "Travel and Meals",
    "holiday inn": "Travel and Meals",
    "courtyard": "Travel and Meals",
    "hampton inn": "Travel and Meals",
    "westin": "Travel and Meals",
    "sheraton": "Travel and Meals",
    "grubhub": "Travel and Meals",
    "doordash": "Travel and Meals",
    "uber eats": "Travel and Meals",
    "seamless": "Travel and Meals",
    "instacart": "Travel and Meals",
    "starbucks": "Travel and Meals",
    "dunkin": "Travel and Meals",
    "panera": "Travel and Meals",
    "panera bread": "Travel and Meals",
    "chipotle": "Travel and Meals",
    "priceline": "Travel and Meals",
    "kayak": "Travel and Meals",

    # ── Utilities (Line 25) ──────────────────────────────────────────────────
    "at&t": "Utilities",
    "att": "Utilities",
    "verizon": "Utilities",
    "t-mobile": "Utilities",
    "tmobile": "Utilities",
    "comcast": "Utilities",
    "xfinity": "Utilities",
    "spectrum": "Utilities",
    "cox": "Utilities",
    "centurylink": "Utilities",
    "lumen": "Utilities",
    "google fiber": "Utilities",
    "frontier communications": "Utilities",
    "pacific gas electric": "Utilities",
    "pg&e": "Utilities",
    "national grid": "Utilities",
    "con edison": "Utilities",
    "conedison": "Utilities",
    "duke energy": "Utilities",
    "dominion energy": "Utilities",
    "eversource": "Utilities",
    "ameren": "Utilities",
    "evergy": "Utilities",
}
